---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: 2mc
  annotations:
spec:
  rules:
    - host: api.rancher
      http:
        paths:
          - backend:
              serviceName: mc
              servicePort: 8000




